# These projects have been completed during training at Practicum data analysys boot camp.
| Sprint | Project | Description | Key words |
| --- | --- | --- | --- |
| 01 | [Python and data analysis basics](https://github.com/darya134/Data_analytics/tree/main/01.%20Python%20and%20data%20analysis%20basics) | This is the introductory project for the Data Analyst course from Practicum. A few simple tasks must be performed with the data of the Ya.Muzyka service during the process. | `pandas`|
| 02 | [Data preprocessing](https://github.com/darya134/Data_analytics/tree/main/02.%20Data%20preprocessing) | A client is the credit department of a bank. It is necessary to find out whether the client's marital status and number of children affect the fact of repaying the loan on time. The bank provides data on the solvency of its customers. | `pandas`|
| 03 | [Exploratory data analysis](https://github.com/darya134/Data_analytics/tree/main/03.%20Exploratory%20data%20analysis) | This project involved the exploratory data analysis of advertisements for the sale of real estate in the St. Petersburg market. The main purpose of this study is to define the key parameters that determine the value of real estate, and to identify potential fraud. | `EDA` `pandas` `matplotlib` `seaborn`|
| 04 | [Statistical data analysis](https://github.com/darya134/Data_analytics/tree/main/04.%20Statistical%20data%20analysis) | An analysis of the costs of different mobile operator tariffs to determine which one brings in more money. As part of the project, statistical hypotheses were also tested. | `pandas` `numpy` `matplotlib` `seaborn` `scipy` `statistics` |
| 05 | [Project-1](https://github.com/darya134/Data_analytics/tree/main/05.%20Project-1) | Data about computer game sales for different platforms is analyzed in the project - an exploratory data analysis is conducted, statistical hypotheses are tested, and conclusions are drawn. | `EDA` `statistics` `pandas`  `matplotlib` `numpy` `seaborn` `scipy` |
| 06 | [Data collection and storage (SQL)](https://github.com/darya134/Data_analytics/tree/main/06.%20Data%20collection%20and%20storage%20(SQL)) | In a Jupyter Notebook, the simplest result of querying a database with air travel data. | `SQL`|
| 07 | [Business analytics](https://github.com/darya134/Data_analytics/tree/main/07.%20Business%20analytics) | The goal is to help marketers reduce costs by eliminating unprofitable traffic sources and redistributing the budget. | `pandas` `numpy` `matplotlib` `seaborn` `DAU` `MAU` `WAU` `CAC` `LTV` `Retention Rate` `ROI`|
| 08 | [Making business decisions based on data](https://github.com/darya134/Data_analytics/tree/main/08.%20Making%20business%20decisions%20based%20on%20data) | An online store is considering various ways to increase conversions. In this project various hypotheses are evaluated using ICE and RICE frameworks. It is also necessary to evaluate the A/B test results. | `pandas` `numpy` `matplotlib` `scipy` `seaborn` `ICE` `RICE` `A/B-test`|
| 09 | [How to tell a story using data](https://github.com/darya134/Data_analytics/tree/main/09.%20How%20to%20tell%20a%20story%20using%20data) | The project requires choosing the most successful format and location for the new catering establishment. Based on the results of the analysis, [a presentation](https://github.com/darya134/Data_analytics/tree/main/01.%20Python%20and%20data%20analysis%20basics) was prepared for stakeholders.  | `EDA` `pandas` `numpy` `matplotlib` `plotly` `seaborn` `scipy`|
| 10 | [Project-2](https://github.com/darya134/Data_analytics/tree/main/10.%20Project-2) | A food startup company needs an analysis of funnel of events. | `EDA` `Funnel of events` `A/B test` `z-test` `pandas` `numpy` `matplotlib` `math` `plotly` `seaborn` `scipy` |
| 11 | [Tableau dashboard](https://github.com/darya134/Data_analytics/tree/main/11.%20Automation) | Employees of the company have requested a dashboard that will allow them to view the most popular card topics in Ya.Zen. | `Tableau` `sqlalchemy` `pandas` |
| 12 | [Forecasts and predictions](https://github.com/darya134/Data_analytics/tree/main/12.%20Forecasts%20and%20predictions) | Сеть фитнес-центров «Культурист-датасаентист» разрабатывает стратегию взаимодействия с клиентами на основе аналитических данных. Формулирование стратегии предполагается осуществлять отталкиваясь от задачи снижения оттока пользователей. | `pandas` `EDA` `seaborn` `numpy` `scipy` `sklearn` `KMeans` `dendrogram` `LogisticRegression` `DecisionTree` `RandomForest`|
| 13-1 | [Final project](https://github.com/darya134/Data_analytics/tree/main/13-1.%20Graduation%20project) | As part of the project, an online store purchase dataset was obtained. The purpose is to analyze the data to identify the features of store development. Audience segmentation based on the available information, finding insights in the results obtained, and formulating recommendations for the development of the store as a whole and for certain categories of customers are the main tasks. Based on the results of the analysis, a [presentation](https://github.com/darya134/Data_analytics/tree/main/01.%20Python%20and%20data%20analysis%20basics) and [dashboard](https://public.tableau.com/app/profile/darya.ilina/viz/Mobile_app_analysis/sheet3#2) was prepared for stakeholders. | `EDA` `A/B test` `pandas`  `seaborn` `numpy` `scipy` `math` `plotly` `sklearn` `matplotlib` `datetime` `Tableau` `MS PowerPoint`|
| 13-2 | [Final project (A/B-test)](https://github.com/darya134/Data_analytics/tree/main/13-2.%20Graduation%20project%20(A/B-test)) | A/B test to test the effectiveness of the new online store recommendation system. | `EDA` `A/B-test` `pandas` `numpy` `matplotlib` `math` `seaborn` `scipy` `plotly` `datetime` |
| 13-3 | [Final project (SQL)](https://github.com/darya134/Data_analytics/tree/main/13-3.%20Graduation%20project%20(SQL)) | A startup has acquired a service for reading books by subscription. Our task is to analyze the existing database. | `SQL` |


![](diploma/diploma_cover_ru.jpg)
![](diploma/diploma_sprints_ru.jpg)

[Версия диплома в PDF](https://github.com/darya134/Data_analytics/tree/main/01.%20Python%20and%20data%20analysis%20basics)

[English version of the diploma](https://github.com/darya134/Data_analytics/tree/main/01.%20Python%20and%20data%20analysis%20basics)
